language: node_js
node_js:
    - "stable"
script:
    - npm run int:test
cache: 
  directories:
    - "node_modules"
addons:
  apt:
    update: true    
after_success:
    - npm run coveralls
services:
    - postgresql
before_script:
    - psql -c 'create database quick_credit_test;' -U postgres
    - psql -c 'create USER chuksEmma WITH PASSWORD null;' -U postgres
    - psql -c `DROP TABLE users IF EXISTS;
CREATE TABLE users(
	Id SERIAL NOT NULL PRIMARY KEY,
	firstName VARCHAR NOT NULL,
	lastName VARCHAR NOT NULL,
  homeAddress VARCHAR NOT NULL,
  organization VARCHAR NOT NULL,
  organizationAddress VARCHAR NOT NULL,
  age INT NOT NULL,
	email VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  status VARCHAR(11) NOT NULL DEFAULT 'unverified',
  isAdmin BOOLEAN NOT NULL
);` -U postgres
env:
  global:
  - NODE_ENV=test
      
