language: node_js
node_js:
    - "10.15.3"
install:
    - npm install
script:
    - npm run int:test
env: 
  - NODE_ENV=test
cache: 
  - npm install
after_success:
    - npm run coveralls
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11  
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE {{your database name here}};' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: bundle exec rake spec
services:
  - postgresql
addons:
  postgresql: "11.3"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
env:
  global: 
    - PGPORT=5433      
      
