env:
  global: 
    - PGPORT=5433    
language: node_js
node_js:
    - "10.15.3"
services:
  - postgresql
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c "CREATE DATABASE quick;" -U postgres
  - psql -c "CREATE USER chuks WITH PASSWORD 'makky3491';" -U postgres
script:
  - "npm run nyc"
  
      
